void handlePortal() {
  if (server.method() == HTTP_POST) {
    strncpy(dughie_setup.ssid,            server.arg("ssid").c_str(),     sizeof(dughie_setup.ssid) );
    strncpy(dughie_setup.password,        server.arg("password").c_str(), sizeof(dughie_setup.password) );
    strncpy(dughie_setup.server_addr,     server.arg("address").c_str(),  sizeof(dughie_setup.server_addr) );
    dughie_setup.ssid[server.arg("ssid").length()] = dughie_setup.password[server.arg("password").length()] = dughie_setup.teks1[server.arg("address").length()] = '\0';
    EEPROM.put(0, dughie_setup);
    EEPROM.commit();

    server.send(200,   "text/html", "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'><title>Dughie Setup</title><style>*,::after,::before{box-sizing:border-box;}body{margin:0;font-family:'Segoe UI',Roboto,'Helvetica Neue',Arial,'Noto Sans','Liberation Sans';font-size:1rem;font-weight:400;line-height:1.5;color:#212529;background-color:#f5f5f5;}.form-control{display:block;width:100%;height:calc(1.5em + .75rem + 2px);border:1px solid #ced4da;}button{border:1px solid transparent;color:#fff;background-color:#007bff;border-color:#007bff;padding:.5rem 1rem;font-size:1.25rem;line-height:1.5;border-radius:.3rem;width:100%}.form-signin{width:100%;max-width:400px;padding:15px;margin:auto;}h1,p{text-align: center}</style> </head> <body><main class='form-signin'> <h1>Dughie Setup</h1> <br/> <p>Your settings have been saved successfully!<br />Please Tap Your Card to restart the device.</p></main></body></html>" );
  }
  else {
    server.send(200,   "text/html", "<!DOCTYPE html> <html lang=\"en\"> <head> <meta charset=\"utf-8\"> <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> <title>Dughie Setup</title> <style> *, ::after, ::before { box-sizing: border-box; } body { margin: 0; font-family: 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', 'Liberation Sans'; font-size: 1rem; font-weight: 400; line-height: 1.5; color: #212529; background-color: #f5f5f5; } .form-control { display: block; width: 100%; height: calc(1.5em + .75rem + 2px); border: 1px solid #ced4da; } button { cursor: pointer; border: 1px solid transparent; color: #fff; background-color: #007bff; border-color: #007bff; padding: .5rem 1rem; font-size: 1.25rem; line-height: 1.5; border-radius: .3rem; width: 100% } .form-signin { width: 100%; max-width: 400px; padding: 15px; margin: auto; } h1 { text-align: center } </style> </head> <body> <main class=\"form-signin\"> <form action=\"/\" method=\"post\"> <h1>Dughie Setup</h1> <div class=\"form-floating\"><label>SSID</label><input type=\"text\" placeholder=\"Masukkan SSID\" class=\"form-control\" name=\"ssid\"></div> <div class=\"form-floating\"><br><label>Password</label><input type=\"password\" placeholder=\"Masukkan Password\" class=\"form-control\" name=\"password\"></div> <div class=\"form-floating\"><br><label>Server Address</label><input type=\"text\" placeholder=\"Masukkan Server Address\" class=\"form-control\" name=\"address\"></div><br><br> <button type=\"submit\">Save</button> </form> </main> </body> </html>");
  }
}
